PACKAGE_NAME="gpd-fan-duo-fix"
PACKAGE_VERSION="0.2"
BUILT_MODULE_NAME[0]="gpd-fan"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hwmon"
PRE_BUILD="fetch-and-patch.sh ${kernelver}"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
AUTOINSTALL="yes"
